version: '3'
services:
  app:
    container_name: btcn_app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - migrate
    networks:
      - btcn

  btcn-postgres:
    image: postgres:latest
    container_name: btcn_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - btcn

  migrate:
    image: migrate/migrate
    container_name: btcn_db_migrate
    depends_on:
      - btcn-postgres
    networks:
      - btcn
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://bitcoin_user:password@btcn-postgres:5432/bitcoin_db?sslmode=disable", "up"]
    links:
      - btcn-postgres
    restart: on-failure

volumes:
  api:
  database_postgres:
  migrate_db:

# Networks to be created to facilitate communication between containers
networks:
  btcn:
    driver: bridge
